# minimum working example of compose file to get jenkins up and running
# jenkins info will be set at /tmp/jenkins on your local -carefull not to
# overwrite (upon reboot or subsequent launching of jenkins) 

---
version: '3.4'
services:
  jenkins:
    build:
      context: .
    privileged: true
    user: root
    ports:
      - 8084:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /tmp/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
